# fly.toml app configuration file generated for shiny-broccoli on 2025-08-30T22:58:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shiny-broccoli'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
