"""create entries table and charts table

Revision ID: 1747990fe23d
Revises: 9bc2f54bdd38
Create Date: 2025-07-19 15:27:20.711340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1747990fe23d'
down_revision: Union[str, None] = '9bc2f54bdd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_charts_deleted_at'), 'charts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_charts_is_deleted'), 'charts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_charts_uuid'), 'charts', ['uuid'], unique=True)
    op.create_table('entries',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('chart_uuid', sa.Uuid(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chart_uuid'], ['charts.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_entries_deleted_at'), 'entries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_entries_is_deleted'), 'entries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_entries_uuid'), 'entries', ['uuid'], unique=True)
    op.add_column('users', sa.Column('uuid', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_column('users', 'uuid')
    op.drop_index(op.f('ix_entries_uuid'), table_name='entries')
    op.drop_index(op.f('ix_entries_is_deleted'), table_name='entries')
    op.drop_index(op.f('ix_entries_deleted_at'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_charts_uuid'), table_name='charts')
    op.drop_index(op.f('ix_charts_is_deleted'), table_name='charts')
    op.drop_index(op.f('ix_charts_deleted_at'), table_name='charts')
    op.drop_table('charts')
    # ### end Alembic commands ###
