"""create code field for charts table

Revision ID: 475883def8b6
Revises: 1747990fe23d
Create Date: 2025-08-11 13:59:31.897383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475883def8b6'
down_revision: Union[str, None] = '1747990fe23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'charts', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charts', type_='unique')
    op.drop_column('charts', 'code')
    # ### end Alembic commands ###
